---
extends:
  - react-app
  - airbnb
  - prettier

parser: babel-eslint

env:
  browser: true
  node: true
  jest: true

settings:
  import/resolver:
    node:
      moduleDirectory:
      - node_modules
      - src

rules:
  react/prop-types: 0
  import/prefer-default-export: 0
